### PR TITLE
Updated BonoboNET service information

### PR DESCRIPTION
**Pull request by deavmi**
Just updated some information regarding BNET that needed to be added

### CODE REVIEW

**Comment by neilalexander** [comment]
Please can we keep this down to essential info only and just put the rest behind the URL?

**Comment by deavmi** [comment]
Sure

**Comment by deavmi** [comment]
Let me just remove the things I added and change the one incorrect thing I added

**Comment by deavmi** [comment]
PR opened as https://github.com/yggdrasil-network/yggdrasil-network.github.io/pull/139

**Pull request closed without merging**
