### PR TITLE
WIP: Fixes #86 - Add OpenWrt platform page

### LINKED ISSUE #86: Platform Notes: missing section for OpenWrt
Looking for content to add in an OpenWrt section. 

- [x] requires snapshots/latest openwrt version
- [x] steps to build using SDK, or ImageBuilder
- [x] link to OpenWrt on GitHub for raising issues (?)
- [x] benchmarks such as RPi4 (no, avoid) 
- Call for feedback (?) 
  - [x] Do we want to support yggdrasil in LuCI GUI? (i'll open PR with latest luci-app-yggdrasil)   
  - [x] Do we want to separate packages: yggdrasilctl, yggdrasil-debug, yggdrasil-genkeys (i'll create issue in openwrt/packages)

### PR DESCRIPTION
**Pull request by wfleurant**

### CODE REVIEW

**Comment by wfleurant** [comment]
- [ ] explain long term / stable support for openwrt-19.07 (expected release this month)
- [ ] trim excess documentation
- [ ] explain using `ygguci` program in openwrt (expected release this month)

**Comment by wfleurant** [comment]
- [ ] explain luci-app-yggdrasil / screenshots

@zhoreeq what else should add/remove here?

**Comment by zhoreeq** [comment]
It also can explain node configuration with UCI. 

Yggdrasil's config options are mapped to corresponding UCI config items. To show all options, one could run:

    uci show yggdrasil

To add a remote peer:

    uci add yggdrasil peer
    uci set yggdrasil.@peer[-1].uri='tcp://2.3.4.5:54321'
    uci commit

**Comment by zhoreeq** [comment]
OpenWrt docs updated in #173 

Close?

**Pull request closed without merging**
