### PR TITLE
Add platform-openwrt.md and update installation.md

### PR DESCRIPTION
**Pull request by Eninspace**
Installation guides for OpenWrt

### CODE REVIEW

**Comment by wfleurant** [comment]
we should add how to install -- take/edit any install or other stuff from here    

https://github.com/yggdrasil-network/yggdrasil-network.github.io/pull/87/files

**Comment by Eninspace** [comment]
Yes, guide how to install there is here https://github.com/yggdrasil-network/yggdrasil-network.github.io/blob/master/installation-linux-openwrt.md

**Comment by Eninspace** [comment]
What we need to add else?

**Comment by megapro17** [comment]
Bump

**Comment by megapro17** [comment]
This gude is not complete, it's saying how to just use yggdrasil. I added ygg0 to br-lan, added public peers but it's still not working at all. When pinging internal site from openwrt it says Permission denied, wtf?

**Comment by wfleurant** [comment]
shitting me? it's very simple just install the packages (daemon and optionally the web  luci app) and it works as expected. @zhoreeq yo...

**Comment by wfleurant** [comment]
i'm a bit annoyed because new routers are multiple cores and can handle a lot of throughout. it's crazy this isn't well documented!

**Comment by neilalexander** [comment]
This PR looks pretty out-of-date I guess, I am guessing there are changes to be merged into https://yggdrasil-network.github.io/installation-linux-openwrt.html ?

**Comment by megapro17** [comment]
> it's very simple just install the packages

And nothing works ffs!

**Comment by wfleurant** [comment]
Alright -- so from the original docs, yggdrasil been supported since OpenWrt 17.01...

- Can we add a screenshot of the web front end `luci-app-yggdrasil` @zhoreeq put some work in here and it's worth the preview.
...screenshot?

- Can we add some heads up of the NodeInfo setup? eg:

```
The Yggdrasil daemon will provide some basic NodeInfo information to the mesh by default. 

"NodeInfo": {
  "kernel": "4.14.123",
  "hostname": "OpenWrt",
  "model": "Globalscale Marvell ESPRESSOBin Board",
  "board_name": "globalscale,espressobin"
}
```
 

- Instead of just saying "... install the package luci-app-yggdrasil" may be we can use something like "to install the yggdrasil service use `opkg install yggdrasil` and to install the web front end install with `opkg install luci-app-yggdrasil`

- Instead of saying "OpenWRT" can we say "OpenWrt"


I think everything else is pretty much straight forward (like adding peers)

@megapro17 you shouldnt have to add yggdrasil interface to your bridge... what are you trying to do? Yggdrasil will broadcast over all (or specific) interfaces if you set it up for this... just creep the OpenWrt chat on Matrix we're paid to help... kidding :)

**Comment by wfleurant** [comment]
@neilalexander the current docs is fine.
we could add info about the default nodeinfo setup.. and that it has been supported since 17.01, why not.  
we should change OpenWRT to OpenWrt in for `installation.html`

This pull request is 2020... Sorry :zzz: for the bitterness.

**Pull request closed without merging**
